### PR TITLE
PLAN-315 session p1 improvements part 1

### PR DESCRIPTION
**Pull request by Gailbear**
- scheduled ticky switch
- proof field & ticky switch
- assigned participants view on flyout
- notes on flyout
- added disabled conflict tab
- format single select in general tab
- commented out tags select in general tab

### CODE REVIEW

**Comment by Gailbear** [comment]
image
updated flyout

**Comment by Gailbear** [comment]
image
updated general tab

**Comment by Gailbear** [comment]
image
updated session summary

**Comment by arbradley** [comment]
pics look good (and quite alike the display on the tv in front of me)

**Pull request merged**
